RevisedProject/Revised/Revised/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('RevisedApp.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

RevisedProject/Revised/RevisedApp/urls.py
from django.urls import path
from RevisedApp import views
from django.contrib.auth import views as ad  

urlpatterns=[
path('',views.homepage,name='home'),
path('abt/',views.abtpage,name='about'),
path('ach/',views.ach,name='ach'),
path('lg/',ad.LoginView.as_view(template_name="html/login.html"),name='log'),
path('lgout/',ad.LogoutView.as_view(template_name="html/logout.html"),name='logo'),
path('reg/',views.register,name='reges'),
path('rol/',views.role,name='main'),
path('req/',views.requestform,name='request'),
path('per/',views.permissions,name='perm'),
path('eper/<int:k>/',views.gvper,name='gp'),
path('das/',views.dashboard,name='dash'),
path('jobs/',views.jobposts,name='job'),
path('ejobs/<int:a>/',views.editjobs,name='editjob'),
path('updf/',views.updf,name='update'),
path('pro/',views.profile,name='profile'),
path('ch/',views.cgf,name='cg'),
path('rst/',ad.PasswordResetView.as_view(template_name='html/resetpassword.html'),name='reset_password'),
path('rst_done/',ad.PasswordResetDoneView.as_view(template_name='html/resetpassworddone.html'),name="password_reset_done"),
path('rst_confirm/<uidb64>/<token>/',ad.PasswordResetConfirmView.as_view(template_name='html/resetpasswordconfirm.html'),name='password_reset_confirm'),
path('rst_cmplt/',ad.PasswordResetCompleteView.as_view(template_name='html/reset_password_complete.html'),name="password_reset_complete"),
path('viewjob/',views.viewjob,name='view'),
path('jobinfo/',views.jobinfo,name='jinfo'),
path('studinfo/',views.studentinfo,name='stdinfo'),
]

RevisedProject/Revised/RevisedApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.

class User(AbstractUser):
	t=[('CSE','CSE'),('ECE','ECE'),('CIVIL','CIVIL'),('Mechanical','Mechanical'),('EEE','EEE'),('MBA','MBA')]
	y=[('III','III'),('IV','IV')]
	rollno=models.CharField(default='17AK1A000',max_length=10)
	dob=models.DateField(null=True)
	year=models.CharField(choices=y,max_length=5,null=True)
	dept=models.CharField(choices=t,max_length=12,null=True)
	phone_no=models.IntegerField(null=True)
	percentage=models.IntegerField(null=True)
	backlogs=models.IntegerField(null=True)
	pass_year=models.IntegerField(null=True)
	address=models.CharField(max_length=250,null=True)
	r=[(1,'coordinator'),(2,'Student'),(3,'Guest')]
	role=models.IntegerField(choices=r,default=3)



class Coordinator(models.Model):
	t=[('CSE','CSE'),('ECE','ECE'),('CIVIL','CIVIL'),('Mechanical','Mechanical'),('EEE','EEE'),('MBA','MBA')]
	cord_name=models.CharField(max_length=10,null=True)
	dept=models.CharField(choices=t,max_length=12,null=True)
	phone_no=models.IntegerField(null=True)


class Jobinfo(models.Model):
	title=models.CharField(max_length=25)
	location=models.CharField(max_length=20)
	salary=models.IntegerField(null=True)
	skills=models.CharField(max_length=30)
	job_role=models.CharField(max_length=30)
	eligible_percent=models.IntegerField(null=True)
	eligible_dept=models.CharField(max_length=30)
	year_of_pass=models.IntegerField(null=True)
	last_date=models.DateField(null=True)
	descrip=models.CharField(max_length=250)
	com_image=models.ImageField(upload_to='Jobs/',default='123.jpg')

RevisedProject/Revised/RevisedApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,PasswordChangeForm
from RevisedApp.models import User,Jobinfo,Coordinator

class UsForm(UserCreationForm):
	password1=forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control","placeholder":"password"}))
	password2=forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control","placeholder":"confirm password"}))
	class Meta:
		model=User
		fields=["username"]
		widgets={
		 "username":forms.TextInput(attrs={"class":"form-control","placeholder":"username"}),
		}

class Cordform(forms.ModelForm):
	class Meta:
		model= Coordinator
		fields= ["cord_name","dept","phone_no"]
		widgets={
		 "cord_name":forms.TextInput(attrs={"class":"form-control","placeholder":"Enter your name"}),
		"dept":forms.Select(attrs = {"class": "form-control",}),
		"phone_no":forms.NumberInput(attrs = {"class": "form-control","placeholder":"Enter your Phone number","required":True}),
		}

class Usperm(forms.ModelForm):
	class Meta:
		model = User
		fields=["username","role"]
		widgets={
		 "username":forms.TextInput(attrs={"class":"form-control","readOnly":True,}),
		 "role":forms.Select(attrs={"class":"form-control"}),
		}


class Jobform(forms.ModelForm):
	class Meta:
		model= Jobinfo
		fields = ["title","location","salary","job_role","skills","descrip"]
		widgets={
		"title":forms.TextInput(attrs={"class":"form-control","placeholder":"Enter company name"}),
		"location":forms.TextInput(attrs={"class":"form-control","placeholder":"Job Location"}),
		"salary":forms.NumberInput(attrs={"class":"form-control","placeholder":"Salary"}),
		"job_role":forms.TextInput(attrs={"class":"form-control","placeholder":"Job Role"}),
		"skills":forms.TextInput(attrs={"class":"form-control","placeholder":"Skills requried"}),
		"descrip":forms.TextInput(attrs={"class":"form-control","placeholder":"Description"})
		}

class UpJobform(forms.ModelForm):
	class Meta:
		model= Jobinfo
		fields= ["job_role","eligible_percent","eligible_dept","year_of_pass","last_date","com_image"]
		widgets={
		"job_role":forms.TextInput(attrs={"class":"form-control","placeholder":"Job role"}),
		"eligible_percent":forms.TextInput(attrs={"class":"form-control","placeholder":"eligible percent"}),
		"eligible_dept":forms.TextInput(attrs={"class":"form-control","placeholder":"eligible_dept"}),
		"year_of_pass":forms.NumberInput(attrs={"class":"form-control","placeholder":"year_of_pass"}),
		"last_date":forms.DateInput(attrs = {"class": "form-control","placeholder":"Last date to apply"},),
		}

class UtupForm(forms.ModelForm):
	class Meta:
		model=User
		fields=["username","email","rollno","dob","year","dept","phone_no","percentage","backlogs","pass_year","address"]
		widgets= {
		"username":forms.TextInput(attrs = {"class": "form-control","placeholder":"Enter your name","required":True}),
		"email":forms.EmailInput(attrs = {"class": "form-control","placeholder":"Enter your Email","required":True}),
		"rollno":forms.TextInput(attrs = {"class": "form-control","placeholder":"Enter your Roll no","required":True}),
		"dob":forms.DateInput(attrs = {"class": "form-control",}),
		"year":forms.Select(attrs = {"class": "form-control",}),
		"dept":forms.Select(attrs = {"class": "form-control",}),
		"phone_no":forms.NumberInput(attrs = {"class": "form-control","placeholder":"Enter your Phone number","required":True}),
		"percentage":forms.NumberInput(attrs = {"class": "form-control","placeholder":"Enter your Percentage","required":True}),
		"backlogs":forms.NumberInput(attrs = {"class": "form-control","placeholder":"Enter your Backlogs","required":True}),
		"pass_year":forms.NumberInput(attrs = {"class": "form-control","placeholder":"Enter your year of pass","required":True}),
		"address":forms.TextInput(attrs = {"class": "form-control","placeholder":"Enter your address","required":True}),
		}

class ChpwdForm(PasswordChangeForm):
	old_password=forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control","placeholder":"Enter your old password"}))
	new_password1=forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control","placeholder":"Enter your new password"}))
	new_password2=forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control","placeholder":"Enter your new confirmation password"}))
	class Meta:
		model=User
		fields="__all__"

RevisedProject/Revised/RevisedApp/views.py
from django.shortcuts import render,redirect
from RevisedApp.forms import UsForm,Usperm,Jobform,UpJobform,UtupForm,ChpwdForm
from django.core.mail import EmailMessage
from Revised import settings
from datetime import date
from RevisedApp.models import User,Jobinfo

# Create your views here.

def homepage(request):
	return render(request,'html/home.html')

def abtpage(self):
	return render(self,'html/abtpage.html')

def  ach(self):
	todays_date = date.today()
	y = {'1':todays_date.year-1,'2':todays_date.year-2,'3':todays_date.year-3,'4':todays_date.year-4,'5':todays_date.year-5}
	return render(self,'html/ach.html',{'y':y})

def register(request):
	if request.method=="POST":
		t=UsForm(request.POST)
		if t.is_valid():
			t.save()
			return redirect('/lg')
	y=UsForm()
	return render(request,'html/register.html',{'t':y})

def role(request):
	# mnp = Jobinfo.objects.all()
	return render(request,'html/mp.html')

def requestform(request):
	if request.method == "POST":
		u=request.POST.get('username')
		r=request.POST.get('rollno')
		d=request.POST.get('dept')
		e=request.POST.get('email')
		at=request.FILES['fe']
		y="Regarding approve request of "+u
		# t= mail_admins("Usesr Role",y)
		t=EmailMessage("Usesr approval",y,settings.EMAIL_HOST_USER,[settings.ADMINS[0][1],e])
		t.content_subtype= 'html'
		t.attach(at.name,at.read(),at.content_type)
		t.send()
		if t == 1:
			return redirect('/req')
	return render(request,'html/request.html')

def permissions(request):
	ty=User.objects.all()
	return render(request,'html/permissions.html',{'q':ty})

def gvper(request,k):
	r=User.objects.get(id=k)
	if request.method == "POST":
		k=Usperm(request.POST,instance=r)
		if k.is_valid():
			k.save()
			return redirect('/per')
	k2= Usperm(instance=r)
	return render(request,'html/gvp.html',{'y':k2})

def dashboard(request):
	a = {'a':50}
	return render(request,'html/dashboard.html',{'a':a})

def jobposts(request):
	w = Jobinfo.objects.all()
	if request.method== "POST":
		e = Jobform(request.POST)
		if e.is_valid():
			e.save()
			return redirect('/jobs')	
	e=Jobform()
	return render(request,'html/jobs.html',{'z':e,'y':w})


def editjobs(request,a):
	t= Jobinfo.objects.get(id=a)
	if request.method== "POST":
		k= UpJobform(request.POST,instance=t)
		if k.is_valid():
			k.save()
			return redirect('/jobs')
	k2 = UpJobform(instance=t)
	return render(request,'html/editjobs.html',{'b':k2})



def profile(req):
	return render(req,'html/profile.html')


def updf(request):
	if request.method == "POST":
		v=UtupForm(request.POST,instance=request.user)
		if v.is_valid():
			v.save()
			return redirect('/pro')
	z=UtupForm(instance=request.user)
	return render(request,'html/updateprofile.html',{'p':z})
	

def cgf(request):
	if request.method == "POST":
		c=ChpwdForm(request.user,data=request.POST)
		if c.is_valid():
			c.save()
			return redirect('/lg')
	c=ChpwdForm(user=request)
	return render(request,'html/changepassword.html',{'p':c})

def viewjob(request):
	return render(request,'html/viewjob.html')

# def deledata(req,id):
# 	data=Jobinfo.objects.get(id=id)
# 	if req.method=="POST":
# 		data.delete()
# 		return redirect('/jobs')
# 	return render(req,'html/deletejob.html',{'sd':data})


def jobinfo(request):
	a = Jobinfo.objects.all()
	return render(request,'html/jobinfo.html',{'t':a})

# def studentinfo(request):
# 	if request.method == "POST":
# 		sid= request.POST['student_id']
# 		c = User(request.POST,instance=request.rollno)
# 		if c.is_valid():
# 			c.save()
# 			return redirect('/studinfo')
# 	b = User.objects.filter(role=2)
# 	return render(request,'html/studentinfo.html',{'u':b})


def studentinfo(request):
	b = User.objects.filter(role=2)
	return render(request,'html/studentinfo.html',{'u':b})

RevisedProject/Revised/RevisedApp/templates/html/abtpage.html
{% extends 'html/base.html' %}
{% load static %}
{% block title %} Home {% endblock %}
{% block content %}
<div class="abtspace">
<section class="abtcontact">	
	<div class="abtcontainer">
		<div class="abtcontactinfo">
			<div class="abtbox">
				<div class="abticon"><i class="fa fa-map-marker" aria-hidden="true"></i></div>
				<div class="abttext">
					<h3>Address</h3>
					<p>6-8-1236, <br> NGOs colont, <br> Tirupati</p>
				</div>
			</div>
			<div class="abtbox">
				<div class="abticon"><i class="fa fa-phone" aria-hidden="true"></i></div>
				<div class="abttext">
					<h3>Phone</h3>
					<p>9121047583</p>
				</div>
			</div>
			<div class="abtbox">
				<div class="abticon"><i class="far fa-envelope"></i></div>
				<div class="abttext">
					<h3>Email</h3>
					<p>loklokesh9876@gmail.com</p>
				</div>
			</div>
		</div>	
		<div class="abtcontactform">
			<form method="POST">
				{% csrf_token %}
				<h2 align="center" style="padding-bottom: 15px; line-height: 1em; font-style: italic; color: blue;">Send Message</h2>
				<div>
					<label for="name" class="">Your name</label>
                    <input type="text" id="name" class="form-control">
                </div>
                <hr>
				<div>
					<label for="mail" class="">Email</label>
                    <input type="text" id="mail" class="form-control">
                </div>
                <hr>
				<div>
					<label for="subject" class="">Subject</label>
                    <input type="text" id="subject" class="form-control">
                </div>
                <hr>
                <input type="submit" value="click" class="btn btn-success col-sm">
			</form>
		</div>	
	</div>
</section>
</div>

{% endblock %}

RevisedProject/Revised/RevisedApp/templates/html/changepassword.html
{% extends 'html/base.html' %}
{% block title %}Change Password {% endblock %}
{% block content %}
<div class="container">
	<div class="card col-md-6 mx-auto mt-4 p-2 shadow-lg">
		<div class="card-body">
			<h3 class="bg-warning text-center text-light p-2 border rounded"> Change Password</h3>
			<form method="POST">
				{% csrf_token %}
				<table class="table table-borderless">
					{% for i in p %}
					<tr>
						<td>{{i}}</td>
					</tr>
					{% endfor %}
				</table>
				<input type="submit" value="Change" class="form-control btn btn-success btn-block my-2 ">
			</form>
			
		</div>
	</div>
</div>
<!-- <!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title></title>
	<style type="text/css">
		@import url(https://fonts.googleapis.com/css?family=Open+Sans:300);
* {
  font-family: 'Open Sans', sans-serif;
}

body {
  margin: 0;
  padding: 0;
  overflow: hidden;
  background: #111;
  background-repeat: no-repeat;
}

.signupSection {
  background: url(https://source.unsplash.com/TV2gg2kZD1o/1600x800);
  background-repeat: no-repeat;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: 800px;
  height: 450px;
  text-align: center;
  display: flex;
  color: white;
  box-shadow: 3px 10px 20px 5px rgba(0, 0, 0, .5);
}

.info {
  width: 45%;
  background: rgba(20, 20, 20, .8);
  padding: 30px 0;
  border-right: 5px solid rgba(30, 30, 30, .8);
  
}
h2 {
    padding-top: 30px;
    font-weight: 300;
  }
  p {
    font-size: 18px;
  }
  .icon {
    font-size: 8em;
    padding: 20px 0;
    color: rgba(10, 180, 180, 1);
  }

.signupForm {
  width: 70%;
  padding: 30px 0;
  background: rgba(20, 40, 40, .8);
  transition: .2s;
  
}
h2 {
    font-weight: 300;
  }

.inputFields {
  margin: 15px 0;
  font-size: 16px;
  padding: 10px;
  width: 250px;
  border: 1px solid rgba(10, 180, 180, 1);
  border-top: none;
  border-left: none;
  border-right: none;
  background: rgba(20, 20, 20, .2);
  color: white;
  outline: none;
}

.noBullet {
  list-style-type: none;
  padding: 0;
}

#join-btn {
  border: 1px solid rgba(10, 180, 180, 1);
  background: rgba(20, 20, 20, .6);
  font-size: 18px;
  color: white;
  margin-top: 20px;
  padding: 10px 50px;
  cursor: pointer;
  transition: .4s;
 
}
 &:hover {
    background: rgba(20, 20, 20, .8);
    padding: 10px 80px;
  }


	</style>
</head>
<body>
	<div class="signupSection">
  <div class="info">
    <h2>Mission to Deep Space</h2>
    <i class="icon ion-ios-ionic-outline" aria-hidden="true"></i>
    <p>The Future Is Here</p>
  </div>
  <form action="#" method="POST" class="signupForm" name="signupform">
    <h2>Sign Up</h2>
    <ul class="noBullet">
      <li>
        <label for="username"></label>
        <input type="text" class="inputFields" id="username" name="username" placeholder="Username" value="" oninput="return userNameValidation(this.value)" required/>
      </li>
      <li>
        <label for="password"></label>
        <input type="password" class="inputFields" id="password" name="password" placeholder="Password" value="" oninput="return passwordValidation(this.value)" required/>
      </li>
      <li>
        <label for="email"></label>
        <input type="email" class="inputFields" id="email" name="email" placeholder="Email" value="" required/>
      </li>
      <li id="center-btn">
        <input type="submit" id="join-btn" name="join" alt="Join" value="Join">
      </li>
    </ul>
  </form>
</div>
</body>
</html> -->
{% endblock %}

RevisedProject/Revised/RevisedApp/templates/html/dashboard.html
{% extends 'html/base.html' %}
{% load static %}
{% block title %}Dashboard{% endblock %}
{% block content %}

			{% if user.is_superuser %}
			<div class="admininfospace">
				<br>
			<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.bundle.min.js'></script>
<script>
    $(document).ready(function() {
        var ctx = $("#chart-line");
        var myLineChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: ['CSE','ECE','EEE','Civil','Mech'],
                datasets: [{
                    data: [150, 140, 30, 40, 88], 
                    label: "Selected Info",
                    borderColor: "green",
                    backgroundColor: 'green',
                    fill: false
                },{
                    data: [30, 40, 40, 50, 92, 180],
                    label: "Non - Selected Info",
                    borderColor: "red",
                    fill: false,
                    backgroundColor: 'red'
                }]
            },
            options: {
                title: {
                    display: true,
                    text: 'Dept wise hired info'
                }
            }
        });
    });
</script>
                <div class="col-sm-6 col-md-4">
                    <div class="card">
                        <div class="card-body" style="height: 280px">
                          	<canvas id="chart-line" width="299" height="200"></canvas>
                        </div>
                    </div>
                </div>
</div>

			{% elif user.role == 1%}
			<h3>Coordinator Dashboard</h3>
			{% else %}
			<div class="studentspace">
			<!DOCTYPE html>
<html>
<head>
	<title>Dashboard</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<style type="text/css">
		* {
	padding: 0;
	margin: 0;
	box-sizing: border-box;
}
.u-name {
	font-size: 20px;
	padding-left: 17px;
}
.u-name b {
	color: #127b8e;
}
.header i {
	font-size: 30px;
	cursor: pointer;
	color: #fff;
}
.header i:hover {
	color: #127b8e;
}
.user-p {
	text-align: center;
	padding-left: 10px;
	padding-top: 25px;
}
.user-p img {
	width: 100px;
	border-radius: 50%;
}
.user-p h4 {
	color: #ccc;
	padding: 5px 0;

}
.side-bar {
	width: 250px;
	background: #262931;
	min-height: 100vh;
	transition: 500ms width;
}
.body {
	display: flex;
}
.section-1 {
	width: 100%;
	color: red;
}
.side-bar ul {
	margin-top: 20px;
	list-style: none;
}
.side-bar ul li {
	font-size: 16px;
	padding: 15px 0px;
	padding-left: 20px;
	transition: 500ms background;
	white-space: nowrap;
	overflow: hidden;
	text-overflow: ellipsis;
}
.side-bar ul li:hover {
	background: #127b8e;
}
.side-bar ul li a {
	text-decoration: none;
	color: #eee;
	cursor: pointer;
	letter-spacing: 1px;
}
.side-bar ul li a i {
	display: inline-block;
	padding-right: 10px;
	font-size: 23px;
}
#navbtn {
	display: inline-block;
	margin-left: 70px;
	font-size: 20px;
	transition: 500ms color;
}
#checkbox {
	display: none;
}
#checkbox:checked ~ .body .side-bar {
	width: 60px;
}
#checkbox:checked ~ .body .side-bar .user-p{
	visibility: hidden;
}
#checkbox:checked ~ .body .side-bar a span{
	display: none;
}

	</style>
</head>
<body>	
<input type="checkbox" id="checkbox">	
	<div class="body">
		<nav class="side-bar">
			<header class="header">
				<label for="checkbox">
					<i class="fa fa-bars" aria-hidden="true"></i>
				</label>
			</header>
			<div class="user-p">
				<img src="{% static 'images/123.jpg' %}">
				<h4>Elias</h4>
			</div>

			<ul>
				<li>
					<a href="#">
						<i class="fa fa-desktop" aria-hidden="true"></i>
						Dashboard
					</a>
				</li>
				<li>
					<a href="#">
							<i class="fa fa-envelope-o" aria-hidden="true"></i>
						Message
					</a>
				</li>
				<li>
					<a href="{% url 'cg' %}">
						<i class="fa fa-info-circle" aria-hidden="true"></i>
						Change Password
					</a>
				</li>
				<li>
					<a href="{% url 'profile' %}">
						<i class="fa fa-cog" aria-hidden="true"></i>
						Profile
					</a>
				</li>
				<li>
					<a href="{% url 'logo'%}">
						<i class="fa fa-power-off" aria-hidden="true"></i>
						Logout
					</a>
				</li>
			</ul>
		</nav>
		<section class="section-1">
			<p>
				hope everything going right...
			</p>
			
<html lang="en">
  <head>
    <title>Document</title>
    <style type="text/css">
      
body{
  font-family: sans-serif;
}

.xyz{
  /*position: absolute;
  top: 40%;
  left: 40%;*/
  padding-left: 100px;
}

.card1{
  height: 200px;
  background-color: white;
}


#cont1:after{
  content: attr(data-pct)"%";
  font-size: 2em;
}

#svg1 circle{
  stroke-dashoffset: 0;
  transition: stroke-dashoffset 1s linear;
  stroke: #ecf0f1;
  stroke-width: 0.6em;


}

#svg1 #bar1{
  stroke: green;
}

    </style>
    
  </head>
  <body>
  <div class="xyz">
    <div class="wrapper1">
      <div class="container1">
        <div class="card1">
          <div id="cont1">
            <svg id="svg1" width="200" height="200">
              <circle r="90" cx="100" cy="100" fill="transparent"></circle>
              <circle id="bar1" r="90" cx="100" cy="100" fill="transparent" stroke-dasharray="565.48" stroke-dashoffset="0"></circle>
            </svg>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    var val = {{ a.a }}
    var $circle = $('#svg1 #bar1');
    var r = $circle.attr('r');
    var c = Math.PI*(r*2);
              
    if (val < 0) { val = 0;}
    if (val > 100) { val = 100;}
                
    var pct = ((100-val)/100)*c;
                
        $circle.css({ strokeDashoffset: pct});
               
        $('#cont1').attr('data-pct',val);
  </script>
</body>
</html>
		</section>
	</div>

</body>
</html>
				
				</div>
		    {% endif %}

{% endblock %}

RevisedProject/Revised/RevisedApp/templates/html/editjobs.html
{% extends 'html/base.html' %}
{% block title %} Job Edit {% endblock %}
{% block content %}


<div class = "container mt-4">
	<div class="card col-md-6 mx-auto">
		<div class="card-body">
		<form method="POST">
			{% csrf_token %}
		<h3>Edit jobs</h3>
		<table class="table table-borderless">
			{% for m in b %}
			<tr>
				<td>{{m}}</td>
			</tr>
			{% endfor %}
		</table>
		<div class="row">
			<div class="col">
				<input type="submit" value="Update Job" class="from-control btn btn-success my-2">
				</div>
			</div>
		</form>
			
	</div>	
	</div>
</div>
<script>
  $( function() {
    $("#id_last_date").datepicker();
  } );
  </script>
{% endblock %}

RevisedProject/Revised/RevisedApp/templates/html/jobs.html
{% extends 'html/base.html' %}
{% block title %}Jobs{% endblock %}
{% block content %}
<div class="container-fluid mt-4">
	<div class="row">
		<div class="col col-md-4 ">
			<div class="card shadow-lg">
				<div class="card-body">
					<h3>Add job</h3>
					<form method="POST">
						{% csrf_token %}
						<table class="table table-borderless">
							<tr>{{z.as_p}}</tr>
						</table>
						<input type="submit" name="Submit" class="btn btn-success col-sm">
                    </form>
                </div>
            </div>
		</div>
		<div class="col col-md ">
			<div class="card shadow-lg">
				<div class="card-body">  
					<h3>Jobs table</h3>
					<table class="table table-borderless">
						<tr class="bg-dark text-light">
							<th>Sno</th>
							<th>Title</th>
							<th>Location</th>
							<th>Salary</th>
							<th>Job Role</th>
							<th>Actions</th>

						</tr>
						{% for t in y %}
						<tr>
							<td>{{forloop.counter}}</td>
							<td>{{t.title}}</td>
							<td>{{t.location}}</td>
							<td>{{t.salary}}</td>
							<td>{{t.job_role}}</td>
							<td colspan="3">
						<a href="{% url 'editjob' t.id %}" class="btn btn-success">Update</a>
						<!-- <a href="#" class="btn btn-info">Update</a> -->
						<a href="#" class="btn btn-danger">Delete</a>
						
					</td>
						</tr>
						{% endfor %}
					</table>
				</div>
			
		</div>
	</div>
</div>
<script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
  </script>
{% endblock %}

RevisedProject/Revised/RevisedApp/templates/html/reset_password_complete.html
{% extends 'html/base.html' %}
{% block title %}Reset Password{% endblock %}
{% block content %}
<div class="container">
<div class="card col-md-6 mt-4 shadow-lg mx-auto">
<div class="card-body">
<h3 class="bg-warning text-center text-light my-2 p-2 border rounded">Reset Passwprd Complete</h3>
<h4>Your password has been reset....Please login to access your account</h4>
</div>
</div>
</div>
{% endblock %}

RevisedProject/Revised/RevisedApp/templates/html/resetpassworddone.html
{% extends 'html/base.html' %}
{% block title %} Reset Password Done {% endblock %}
{% block content %}
<div class="container">
	<div class="card col-md-5 mx-auto shadow-lg mt-5">
		<h3 class="bg-dark text-center text-light mt-2 p-2 border rounded ">Reset Password Done</h3>
		<div class="card-body">
			<h4>Your password has been reset. Please check your Email Id </h4>
		</div>
	</div>
</div>
{% endblock %}